---
title: "NYC Restaurants"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: logo.png
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
library(packrat)
library(rsconnect)
library(knitr)
library(DT)
df <- read_csv("https://aileen-charron.github.io/M460_Statistical_Analysis_with_R/food_order.csv")

df <- df %>% 
  filter(rating != "Not given")

df_summary <- df %>%
  group_by(restaurant_name, cuisine_type) %>%
  summarise(
    avg_cost_of_the_order = round(mean(cost_of_the_order, na.rm = TRUE), 2),  
    avg_rating = round(mean(as.numeric(rating), na.rm = TRUE), 2),
    avg_prep_time = round(mean(food_preparation_time, na.rm = TRUE), 0),  
    avg_delivery_time = round(mean(delivery_time, na.rm = TRUE), 0),  
    avg_total_time = round(avg_prep_time + avg_delivery_time, 0),     
    num_ratings = sum(!is.na(rating) & rating != "Not given") 
  ) %>%
  select(
    restaurant_name, cuisine_type, avg_cost_of_the_order, avg_rating, 
    avg_prep_time, avg_delivery_time, avg_total_time, num_ratings  
  )



df_summary <- df_summary %>% 
  mutate(num_reviews_5_plus = ifelse(num_ratings >= 5, "five or more", "less than five"))


df_summary <- df_summary %>% 
  mutate(four_plus_rating = ifelse(avg_rating>=4, "rated 4 or more", "rated less than 4"))


review_five <- unique(df_summary$num_reviews_5_plus)
```

#  {.sidebar}

NYC Restaurants Data - Food Ordering and Delivery. Looking to see how ratings (1-5) vary by other factors.

```{r}
checkboxGroupInput(inputId = "cuisine_type_input", 
                   label = h3("Cuisine Type"),
                   choices = unique(df_summary$cuisine_type), 
                   inline = TRUE,
                   selected = 'S')
```

```{r}
selectInput(inputId = "five_plus_input", 
            label = h3("Select Review Amount For Restaurant"),
            choices = review_five, 
            selected = "five or more")
```

```{r}
sliderInput(inputId = "price_input",
            label = h2("Select Cost of Order"),
            min = min(df_summary$avg_cost_of_the_order, na.rm=TRUE),
            max = max(df_summary$avg_cost_of_the_order, na.rm=TRUE),
            value= c(10, 20))
```


```{r}
sliderInput(inputId = "time_input",
            label = h2("Total Time (Prep + Delivery)"),
            min = min(df_summary$avg_total_time, na.rm=TRUE),
            max = max(df_summary$avg_total_time, na.rm=TRUE),
            value= c(10, 20))
```


# Top 5 Restaurants

## Column {data-width="500"}

### Top 5 Restaurants by Number of Ratings

```{r}
renderPlotly({p1 <-df_summary %>% 
  filter(cuisine_type%in%input$cuisine_type_input) %>% 
      filter(num_reviews_5_plus == input$five_plus_input) %>% 
      filter(avg_cost_of_the_order>input$price_input[1], avg_cost_of_the_order<input$price_input[2]) %>% 
  filter(avg_total_time>input$time_input[1], avg_total_time<input$time_input[2]) %>% 
  arrange(desc(num_ratings)) %>% 
  head(5) %>% 
  ggplot(aes(x = reorder(restaurant_name, -num_ratings), y = num_ratings))+
    geom_bar(stat = "identity") +
    labs(
      x = "Restaurant Name",
      y = "Number of Ratings"
    )+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  ggplotly(p1)
})
```

## Column {data-width="500"}

### Average Rating of Top 5 Restaurants by Rating

```{r}
renderPlotly({p2 <- df_summary %>% 
    filter(cuisine_type%in%input$cuisine_type_input) %>% 
        filter(num_reviews_5_plus == input$five_plus_input) %>% 
  filter(avg_cost_of_the_order>input$price_input[1], avg_cost_of_the_order<input$price_input[2]) %>% 
  filter(avg_total_time>input$time_input[1], avg_total_time<input$time_input[2]) %>% 
  arrange(desc(num_ratings)) %>% 
  head(5) %>% 
  ggplot(aes(x = reorder(restaurant_name, -num_ratings), y = avg_rating)) + 
           geom_bar(stat = "identity") +
           labs(x = "Restaurant Name",
                y = "Average Rating") +
           theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggplotly(p2) })
```

